### ISSUE TITLE
BUG: Auth error is thrown when communicating with Guidence Engine

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/virtual-contributor-engine-guidance#68]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/
2. Authenticate 
3. Ask "who is the founder of Alkemio" - auth error is thrown: `"message": "AuthorizationPolicy without credential rules provided: 5111244c-9262-4620-ae44-021a787d9ef5, type: profile",`

**Expected behavior**
Error is not thrown.

**Comment by valentinyanakiev** [comment]
I've reviewed the code, auth reset should fix it for existing users, for new ones trying to use the engine, it should already be properly created
